export const arianaVille = [
  { name: "Ariana", _id: "Ariana" },
  { name: "Borj El Baccouche", _id: "Borj El Baccouche" },
  { name: "Centre Commercial Ikram", _id: "Centre Commercial Ikram" },
  { name: "Cité Belvédère 2", _id: "Cité Belvédère 2" },
  { name: "Cité Borj Turki 1", _id: "Cité Borj Turki 1" },
  { name: "Cité Borj Turki 5", _id: "Cité Borj Turki 5" },
  { name: "Cité de la Santé", _id: "Cité de la Santé" },
  { name: "Cité des Rose", _id: "Cité des Rose" },
  { name: "Cité du Jardin", _id: "Cité du Jardin" },
  { name: "Cité du Printemps", _id: "Cité du Printemps" },
  { name: "Cité du Soleil", _id: "Cité du Soleil" },
  { name: "Cité El Intissar 1", _id: "Cité El Intissar 1" },
  { name: "Cité El Intissar 2", _id: "Cité El Intissar 2" },
  { name: "Cité Ennasr 1", _id: "Cité Ennasr 1" },
  { name: "Cité Ennasr 2", _id: "Cité Ennasr 2" },
  { name: "Cité Ennozha", _id: "Cité Ennozha" },
  { name: "Cité Essaada (Ariana)", _id: "Cité Essaada (Ariana)" },
  {
    name: "Cité Essaada (Riadh El Andalous)",
    _id: "Cité Essaada (Riadh El Andalous)"
  },
  { name: "Cité Jaafar", _id: "Cité Jaafar" },
  { name: "Cité Jamil", _id: "Cité Jamil" },
  { name: "Cité Karim", _id: "Cité Karim" },
  { name: "Cité Mehrzia 1", _id: "Cité Mehrzia 1" },
  { name: "El Menzah 5", _id: "El Menzah 5" },
  { name: "El Menzah 6", _id: "El Menzah 6" },
  { name: "El Menzah 7", _id: "El Menzah 7" },
  { name: "El Menzah 8", _id: "El Menzah 8" },
  { name: "Nouvelle Ariana", _id: "Nouvelle Ariana" },
  { name: "Résidence El Ons", _id: "Résidence El Ons" },
  { name: "Résidence Ennour (Ariana)", _id: "Résidence Ennour (Ariana)" },
  { name: "Résidence Ennour (Nasr 1)", _id: "Résidence Ennour (Nasr 1)" },
  { name: "Résidence Ennour (Nasr 2)", _id: "Résidence Ennour (Nasr 2)" },
  { name: "Résidence Ibn Zeidoun", _id: "Résidence Ibn Zeidoun" },
  { name: "Résidence Ichbilia", _id: "Résidence Ichbilia" },
  { name: "Résidence Kortoba", _id: "Résidence Kortoba" },
  { name: "Riadh El Andalous", _id: "Riadh El Andalous" }
];

export const ettadhamon = [
  { name: "Cité 18 Janvier", _id: "Cité 18 Janvier" },
  { name: "Cité Ben Yerfes", _id: "Cité Ben Yerfes" },
  { name: "Cité El Houda", _id: "Cité El Houda" },
  { name: "Cité Ennasser", _id: "Cité Ennasser" },
  { name: "Cité Ettadhamon", _id: "Cité Ettadhamon" },
  { name: "Cité Ettayarene", _id: "Cité Ettayarene" },
  { name: "Cité Sfar", _id: "Cité Sfar" },
  { name: "Cité Snit 2", _id: "Cité Snit 2" },
  { name: "Cité Snit Nagra", _id: "Cité Snit Nagra" }
];

export const kalaatElAndalous = [
  { name: "Borj El Hadj", _id: "Borj El Hadj" },
  { name: "Cité Bir El Araies", _id: "Cité Bir El Araies" },
  { name: "Cité des Martyrs", _id: "Cité des Martyrs" },
  { name: "Cité El Fejja", _id: "Cité El Fejja" },
  { name: "Cité El Mourouj", _id: "Cité El Mourouj" },
  { name: "Cité El Oulja", _id: "Cité El Oulja" },
  { name: "Cité Essibous", _id: "Cité Essibous" },
  { name: "Cité Tarek Ibn Zied", _id: "Cité Tarek Ibn Zied" },
  { name: "El Misra", _id: "El Misra" },
  { name: "Ferme Hababou", _id: "Ferme Hababou" },
  { name: "Ferme Mustapha", _id: "Ferme Mustapha" },
  { name: "Henchir Touba", _id: "Henchir Touba" },
  { name: "Henchir Toubias", _id: "Henchir Toubias" },
  { name: "Kalaar el Andalous", _id: "Kalaar el Andalous" },
  { name: "Pont de Bizerte", _id: "Pont de Bizerte" }
];
